version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leistungskurve
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mixpost_default

  app:
    build: .
    container_name: ekg_app
    ports:
      - "8502:8502"
    environment:
      - DATABASE_URL=postgresql://leistungs_user:password@db:5432/leistungskurve
    depends_on:
      - db
    networks:
      - mixpost_default

volumes:
  db_data:
    driver: local

networks:
  mixpost_default:
    external: true
