version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  app:
    build: .
    container_name: ekg_app
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://leistungs_user:password@db:5432/leistungskurve
    depends_on:
      - db

volumes:
  db:
    driver: local
