FROM postgres:14.1-alpine

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=leistungskurve

# Copy the initialization script and entry script
COPY setup.sql /docker-entrypoint-initdb.d/
COPY init.sh /docker-entrypoint-initdb.d/

# Make the script executable
RUN chmod +x /docker-entrypoint-initdb.d/init.sh

USER postgres

# Run init.sh
ENTRYPOINT ["/docker-entrypoint-initdb.d/init.sh"]